# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and release"
  lane :staging do
    setup_ci if ENV['CI']
    sh('cp', '../src/config/staging.ts', '../src/config/index.ts')
    update_code_signing_settings(
      use_automatic_signing: false,
      path: './ios/FHIRmHealth.xcodeproj',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      bundle_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      code_sign_identity: 'Apple Distribution: Илья Беда (4452VN45AX)',
      profile_name: 'match AppStore software.beda.fhirmhealth.fhirmhealth',
    )
    match(type: "appstore", readonly: true)
    build_ios_app(
      workspace: './ios/FHIRmHealth.xcworkspace',
      clean: true,
      suppress_xcode_output: true
    )
    appstore_api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT'],
    )
    upload_to_testflight(api_key=appstore_api_key)
  end
end
